# Data Types and Data Structures


# Python Variables

- are assigned with ```=```
- are *dynamically typed* (have no static type)
- are pointers
- variable names:
    - must begin with a letter (lower or upper case) or underscore _
    - may contain letters, numbers and underscore, but cannot begin with a number
    - are case sensitive


## Python Variables are assigned with ```=```

In [1]:
# assign 4 to the variable x
x = 4 
print(x)

4


## Python Variables are passed-by-reference
In contrast, Java variables are passed-by-value

In [2]:
x = 3.1415   # define a container in memory with value 3.1415 and assign variable/pointer x to it
y = x        # assign a second variable y that points to the same location as x
print(x)
print(y)
print(id(x)) # address of the container x is pointing at
print(id(y))

3.1415
3.1415
1517492552688
1517492552688


In [3]:
x = 2.71     # define a new container with value 2.71 and reassign pointer x to the new location
print(x)
print(y)
print(id(x))
print(id(y))

2.71
3.1415
1517493075120
1517492552688



**Note**: Java would have modified the same container *x* changing the value 3.1415 to 2.71.

In contrast, Python creates 2 containers (one with value 3.1415, one with value 2.71) and just reassigns the pointer *x*.

In [4]:
# Bonus:
x += 3       # this also creates another container with the value 2.71 + 3 = 5.71
print(x)
print(id(x))

5.71
1517493075216


Note: Python differentiates between **immutable** objects (``int``, ``float``, ``bool``, ``str``, ``tuple``) and **mutable** ones (``list``, ``dict``, ``set``). 

More on this later.

## Python Variables are 'dynamically typed'

In [5]:
x = 1         # x is an integer
print(x)
x = 'hello'   # now x is a string
print(x)
x = [1, 2, 3] # now x is a list
print(x)

1
hello
[1, 2, 3]


## Dynamic Typing

- Type only known at runtime
- Can result in semantic errors

In [6]:
# a function for multiplying numbers by two:
def multiply_by_two(x):
    return x * 2

x = 2 # x is an integer
print(multiply_by_two(x))

4


In [7]:
x = "2" # x is a string
print(multiply_by_two(x))

22



- 'Normal' (that is *static*) typing: variable is declared to be of certain type
```
int c = 0;
```

- Python does not have variables with static types (but see [mypy](http://mypy-lang.org/examples.html))


## How to check types by introspection

In [8]:
x = 1         # x is an integer
type(x)

int

In [9]:
x = "1"         # x is a string
type(x)

str

In [10]:
x = [1]         # x is a list
type(x)

list

In [11]:
x = [1]         # x is a list
issubclass(type(x), list)

True

# Python Scalar Types

| Type        | Example        | Description                                                  |
|-------------|----------------|--------------------------------------------------------------|
| ``int``     | ``x = 1``      | integers (i.e., whole numbers)                               |
| ``float``   | ``x = 1.0``    | floating-point numbers (i.e., real numbers)                  |
| ``complex`` | ``x = 1 + 2j`` | Complex numbers (i.e., numbers with real and imaginary part) |
| ``bool``    | ``x = True``   | Boolean: True/False values                                   |
| ``str``     | ``x = 'abc'``  | String: characters or text                                   |
| ``NoneType``| ``x = None``   | Special object indicating nulls                              |


*Note 1*: Python 2 had an extra type `long` for very large values, which got replaced by `int` in Python 3.

*Note 2*: There is no size limit to the Python 3 `int` - you can theoretically run out of memory by adding integers :^)

## Integers

In [12]:
x = 1
type(x)

int

In [13]:
# python ints are automatically casted to floats
x / 2

0.5

## Floats

In [14]:
x = 1.
type(x)

float

In [15]:
# explicit cast
x = float(1)
type(x)

float

In [16]:
# equality checks between floats and ints actually work
x == 1

True

### Exponential notation

``e`` or ``E`` can be read "...times ten to the...",
so that ``1.4e6`` is interpreted as $~1.4 \times 10^6$


In [17]:
x = 1400000.00
y = 1.4e6
print(x == y)

True


Fun facts:
- maximum float value on a 64-bit computer: `1.7976931348623157e+308`
- minimum float value: `2.2250738585072014e-308`
- Python floats use *double precision* with 53 bits -> precision up to 16 digits; if you need more, use `Decimal` 
- computers are binary machines -> floats are stored as integers and then divided by a power of 2, more infos [here](http://docs.python.org/tutorial/floatingpoint.html)

## None Type
Similar to null in Java

In [18]:
return_value = print('abc')
type(return_value)

abc


NoneType

## Boolean Type

- ```True``` and ```False```
- Case sensitive!

In [19]:
result = (4 < 5)
result

True

In [20]:
type(result)

bool

### Many types are implicitly cast to booleans:

### Numbers

In [21]:
bool(2014)

True

In [22]:
bool(0)

False

### None Types (or any other Type)

In [23]:
bool(None)

False

### Strings

In [24]:
bool("")

False

In [25]:
bool("abc")

True

### Lists

In [26]:
bool([1, 2, 3])

True

In [27]:
bool([])

False

# Operators
- Arithmetic Operators
- Bitwise Operators
- Assignment Operators
- Comparison Operators
- Boolean Operators
- Membership Operators


## Arithmetic Operations

| Operator     | Name           | Description                                            |
|--------------|----------------|--------------------------------------------------------|
| ``a + b``    | Addition       | Sum of ``a`` and ``b``                                 |
| ``a - b``    | Subtraction    | Difference of ``a`` and ``b``                          |
| ``a * b``    | Multiplication | Product of ``a`` and ``b``                             |
| ``a / b``    | True division  | Quotient of ``a`` and ``b``                            |
| ``a // b``   | Floor division | Quotient of ``a`` and ``b``, removing fractional parts |
| ``a % b``    | Modulus        | Integer remainder after division of ``a`` by ``b``     |
| ``a ** b``   | Exponentiation | ``a`` raised to the power of ``b``                     |
| ``-a``       | Negation       | The negative of ``a``                                  |
| ``+a``       | Unary plus     | ``a`` unchanged (rarely used)                          |


In [28]:
a = 12
b = 3
a + b

15

In [29]:
# Operator precedence
print(a + b / 3 - 4 * 12)

-35.0


## Bitwise Operations

| Operator     | Name            | Description                                 |
|--------------|-----------------|---------------------------------------------|
| ``a & b``    | Bitwise AND     | Bits defined in both ``a`` and ``b``        |
| <code>a &#124; b</code>| Bitwise OR      | Bits defined in ``a`` or ``b`` or both      |
| ``a ^ b``    | Bitwise XOR     | Bits defined in ``a`` or ``b`` but not both |
| ``a << b``   | Bit shift left  | Shift bits of ``a`` left by ``b`` units     |
| ``a >> b``   | Bit shift right | Shift bits of ``a`` right by ``b`` units    |
| ``~a``       | Bitwise NOT     | Bitwise negation of ``a``                          |

In [30]:
a = True
b = False
a & b

False

## Assignment Operations

| $~ $     | $~ $           | $~ $                                 |
|--------------|-----------------|---------------------------------------------|
|``a += b``| ``a -= b``|``a *= b``| ``a /= b``|
|``a //= b``| ``a %= b``|``a **= b``|``a &= b``|
|<code>a &#124;= b</code>| ``a ^= b``|``a <<= b``| ``a >>= b``|

In [31]:
a = 2
print(id(a))

# 'Normal' Assignment
a = a + 2  # equivalent to a = a + 2, but more efficient (it only evaluates 'a' once)

print(a)
print(id(a)) # new address

1517403597136
4
1517403597200


In [32]:
a = 2
print(id(a))

# Augmented Assignment
a += 2  # equivalent to a = a + 2, but more efficient (it only evaluates 'a' once)

# However: still new container created (integers are immutable)

print(a)
print(id(a)) # new address

1517403597136
4
1517403597200


## Boolean Operations

| Operator      | Description                                       |
|---------------|---------------------------------------------------|
| ``a and b``    | True if ``a`` and ``b``     |
| ``a or b``| True if ``a`` or ``b`` is true |
| ``not a``    | True if ``a`` is false.|

In [33]:
True and False

False

In [34]:
[True, True] or [False, True]

[True, True]

In [35]:
[True, True, True] and [True, False, 2]

[True, False, 2]

How does ``and`` and ``or`` process non-boolean values?
See https://stackoverflow.com/questions/47007680/how-do-and-and-or-act-with-non-boolean-values

## Comparison Operations

| Operation     | Description                       | Operation     | Description                          |
|---------------|-----------------------------------|---------------|--------------------------------------|
| ``a == b``    | ``a`` equal to ``b``              | ``a != b``    | ``a`` not equal to ``b``             |
| ``a < b``     | ``a`` less than ``b``             | ``a > b``     | ``a`` greater than ``b``             |
| ``a <= b``    | ``a`` less than or equal to ``b`` | ``a >= b``    | ``a`` greater than or equal to ``b`` |

In [36]:
# 25 is odd
25 % 2 == 1

True

In [37]:
# check if a is between 15 and 30
a = 25
15 < a < 30

True

In [38]:
# comparisons on standard collections are not elementwise
[1,3] == [2,2]

False

In [39]:
# but
a = [1,2]
b = a
a == b

True

In [40]:
# Check if the address is the same
a is b

True

In [41]:
c = [1,2]
c is a

False

## Identity and Membership Operators

| Operator      | Description                                       |
|---------------|---------------------------------------------------|
| ``a is b``    | True if ``a`` and ``b`` are identical objects     |
| ``a is not b``| True if ``a`` and ``b`` are not identical objects |
| ``a in b``    | True if ``a`` is a member of ``b``                |
| ``a not in b``| True if ``a`` is not a member of ``b``            |

In [42]:
1 in [1,2,3]

True

## Strings

- Python is great for Strings
- String encoding is a good reason to not use Python 2

### Some Useful String Functions

In [43]:
message = "The answer is "
answer = '42'

In [44]:
# length of string
len(answer)

2

In [45]:
# Make upper-case. See also str.lower()
message.upper()

'THE ANSWER IS '

In [46]:
# Concatenation 
message + answer

'The answer is 42'

In [47]:
# Multiple arguments
print(message, answer)

The answer is  42


In [48]:
# All arguments must be strings when concatenating
answer2 = 42
print(message, answer2)       # this works
print(message + str(answer2)) # this, too
print(message + answer2)      # this doesn't

The answer is  42
The answer is 42


TypeError: can only concatenate str (not "int") to str

In [49]:
# String-multiplication
answer * 3

'424242'

In [50]:
# User interactivity
greeting = "Nice to meet you, "
name = input("What is your name? ")
print(greeting + name)

What is your name?  Amy


Nice to meet you, Amy


In [51]:
# The escape character '\'
lines = "Welcome to the DataPy! \nPython rocks!"
lines

'Welcome to the DataPy! \nPython rocks!'

In [52]:
print(lines)

Welcome to the DataPy! 
Python rocks!


In [53]:
print("1\t2\t3\t4")

1	2	3	4


In [54]:
print("And then I said: \"What?! Get out of here!\"")
# or
print('And then I said: "What?! Get out of here!"')
# or
print("""And then I said: "What?! Get out of here!" """)

And then I said: "What?! Get out of here!"
And then I said: "What?! Get out of here!"
And then I said: "What?! Get out of here!" 


In [55]:
# Can be problematic with file paths
print("C:\Documents\butterball\notebooks")

C:\Documentutterball
otebooks


In [56]:
# Use double backslash then
print("C:\\Documents\\butterball\\notebooks")
# Or raw string
print(r"C:\Documents\butterball\notebooks")

C:\Documents\butterball\notebooks
C:\Documents\butterball\notebooks


In [57]:
# Accessing individual characters (zero-based indexing)
message[0]

'T'

In [58]:
message[14]

IndexError: string index out of range

In [59]:
# Negative indexing
message[-1]

' '

In [60]:
message[-2]

's'

In [61]:
message[0] == message[-14]

True

In [62]:
# Negative index = positive index - string length
len_msg = len(message)
print(message[4])
print(message[4 - len_msg])

a
a


Strings are a so-called *sequence type*; in this case, they are a sequence of characters. Apart from elementwise index accessing, sequences can also be *sliced*.

In [63]:
message[0:3] # character from 0 up to BUT NOT INCLUDING 3

'The'

In [64]:
message[:3] # left index is 0 by default

'The'

In [65]:
message[4:10]

'answer'

In [66]:
message[4:] # right index is the end of string by default

'answer is '

In [67]:
message[:] # What will this output?

'The answer is '

In [68]:
message[:]

'The answer is '

*Note*: blank slincing is not really helpful when dealing with strings. However, it can be really useful when manipulating lists. 

In [69]:
# Multiline strings
multiline_string = """Computers are useless. 
They can only give you answers.
"""
print(multiline_string)

Computers are useless. 
They can only give you answers.



In [70]:
# Multiline strings
multiline_string_no_more = """Computers are useless. \
They can only give you answers.
"""
print(multiline_string_no_more)

Computers are useless. They can only give you answers.



In [71]:
# Striping off unnecessary blanks (including \n or \t)
line = '         this is the content         '
line.strip()

'this is the content'

In [72]:
# Finding substrings
line = 'the quick brown fox jumped over a lazy dog'
line.find('fox')

16

In [73]:
line.find('bear')

-1

In [74]:
# Simple replacements
line.replace('brown', 'red')

'the quick red fox jumped over a lazy dog'

In [75]:
# Splitting a sentence into words
line.split()

['the', 'quick', 'brown', 'fox', 'jumped', 'over', 'a', 'lazy', 'dog']

In [76]:
# Joining them back together
'--'.join(line.split())

'the--quick--brown--fox--jumped--over--a--lazy--dog'

### String Formatting

In [77]:
x = 3.14159
"This is a bad approximation of pi: " + str(x)

'This is a bad approximation of pi: 3.14159'

In [78]:
"This is a bad approximation of pi: {}".format(x)

'This is a bad approximation of pi: 3.14159'

In [79]:
y = 3
"This is a bad approximation of pi: {} but better than {}".format(x, y)

'This is a bad approximation of pi: 3.14159 but better than 3'

In [80]:
"This is a bad approximation of pi: {1} but better than {0}".format(y, x)

'This is a bad approximation of pi: 3.14159 but better than 3'

In [81]:
"""This is a bad approximation of pi: {bad} but better than {worse}""".format(bad=x, worse=y)

'This is a bad approximation of pi: 3.14159 but better than 3'

In [82]:
"Both of these approximations of pi are bad: {0:.3f} and {1}".format(x,y)

'Both of these approximations of pi are bad: 3.142 and 3'

### Since Python 3.6: f-String interpolation

In [83]:
width = 5
precision = 3
f'Bad approximation, nice f-string interpolation formatting: {x:{width}.{precision}}'

'Bad approximation, nice f-string interpolation formatting:  3.14'

In [84]:
x = 3.14
f'Pi is {x}.'

'Pi is 3.14.'

# Data Structures

## Built-in Python Data Structures

| Type Name | Example                          | Index Access | Mutable | Duplicates   |
|-----------|----------------------------------|--------------|---------|--------------|
| ``list``  | ``[1, 2, 3, 2]``                 | Yes          | Yes     | Yes          |
| ``tuple`` | ``(1, 2, 3, 2)``                 | Yes          | No      | Yes          |
| ``dict``  | ``{'a':1, 'b':2, 'c':3, 'd':2}`` | No           | Yes     | Yes (Values) |
| ``set``   | ``{1, 2, 3, 4}``                 | No           | Yes     | No           |


Note: *lists*, *tuples* (and also *ranges* and *strings*) are commonly known as **Python Sequences** (= **ordered** collections of items).

## Lists

- Ordered, indexable
- Zero-based indexing
- Mutable
- Can contain duplicates
- Defined by ``[ ]`` 


### List Indexing - Accessing Single Elements

In [85]:
L = [2, 3, 5, 7, 11]
L[0]

2

In [86]:
L[1]

3

In [87]:
L[-1]

11

In [88]:
L[-2]

7

In [89]:
# Length of the list
len_L = len(L)
len_L

5

### List Slicing - Accessing Multiple Elements

In [90]:
L[0:3]

[2, 3, 5]

In [91]:
L[:len_L]

[2, 3, 5, 7, 11]

In [92]:
L[:3]

[2, 3, 5]

In [93]:
L[-3:]

[5, 7, 11]

In [94]:
L[-3:-1]

[5, 7]

In [95]:
# Slicing with steps
L[0:5:2]

[2, 5, 11]

In [96]:
L[-1: :-2]

[11, 5, 2]

In [97]:
L[::2]  # equivalent to L[0:len(L):2]

[2, 5, 11]

In [98]:
L[::-1] # reverses a list

[11, 7, 5, 3, 2]

### List Indexing and Slicing for Accessing and Assigning Elements

In [99]:
L[0] = 100
L

[100, 3, 5, 7, 11]

In [100]:
L[1:3] = [55, 56]
L

[100, 55, 56, 7, 11]

### Operations with Lists

In [101]:
L + [20, 30] # Concatenation

[100, 55, 56, 7, 11, 20, 30]

In [102]:
L - [2] # Sorry, no subtraction :^(

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [103]:
L.append(10) # Add '10' at the end
L

[100, 55, 56, 7, 11, 10]

In [104]:
L.pop(-1) # Remove last item
L

[100, 55, 56, 7, 11]

In [105]:
L.remove(7) # Remove item '3'
L

[100, 55, 56, 11]

In [106]:
L.insert(3, 1) # Insert 1 at position 3
L

[100, 55, 56, 1, 11]

In [107]:
L.sort() # sorts a list in-place (no copy created)
print(L)
L.sort(reverse=True)
print(L)

[1, 11, 55, 56, 100]
[100, 56, 55, 11, 1]


In [108]:
sorted_L = sorted(L) # sorts the list and returns a copy
print(L)
print(sorted_L)

[100, 56, 55, 11, 1]
[1, 11, 55, 56, 100]


In [109]:
# Copy a list
L2 = L.copy()
L2

[100, 56, 55, 11, 1]

There are 12 ways of copying a list in Python, some more efficient than others:

https://stackoverflow.com/questions/2612802/how-do-i-clone-a-list-so-that-it-doesnt-change-unexpectedly-after-assignment/43220129#43220129

### Pointers to Lists: Shallow vs Deep Copies

#### Scenario 1

In [110]:
# What's happening here?
a = [1, 2, 3, 5] 
print(a)
b = a       
print(b)    
a = a + [8] 
            
print(a)    
print(b)

[1, 2, 3, 5]
[1, 2, 3, 5]
[1, 2, 3, 5, 8]
[1, 2, 3, 5]


#### Scenario 1

In [111]:
# What's happening here?
a = [1, 2, 3, 5] # Define a list container and point at it through pointer a
print(a)
b = a       # A new pointer b pointing to the same container as pointer a
print(b)    # Pointer b points to the same container as a
a = a + [8] # From right to left: access container from a, extend it with '8', store somewhere else in memory 
            # and reassign pointer a to the new location 
print(a)    # Pointer a points to the new extended container
print(b)    # Pointer b points to the original container

[1, 2, 3, 5]
[1, 2, 3, 5]
[1, 2, 3, 5, 8]
[1, 2, 3, 5]


*Note*: Adding / concatenating lists together via `+` creates a new list.

#### Scenario 1.1

In [112]:
# What's happening here?
a = [1, 2, 3, 5] 
print(a)
b = a       
print(b)    
a += [8]    

print(a)    
print(b)    

[1, 2, 3, 5]
[1, 2, 3, 5]
[1, 2, 3, 5, 8]
[1, 2, 3, 5, 8]


#### Scenario 1.1

In [113]:
# What's happening here?
a = [1, 2, 3, 5] # Define a list container and point at it through pointer a
print(a)
b = a       # A new pointer b pointing to the same container as pointer a
print(b)    # Pointer b points to the same container as a
a += [8]    # Augmented Assignment: the original container is modified in-place without creating a new one

print(a)    # Pointer a points to the original (now extended) container
print(b)    # Pointer b points to the original (now extended) container

[1, 2, 3, 5]
[1, 2, 3, 5]
[1, 2, 3, 5, 8]
[1, 2, 3, 5, 8]


#### Scenario 2

In [114]:
# What's happening here?
a = [1, 2, 3, 5] 
print(a)
b = a       
print(b)    
a.append(8)          
print(a)    
print(b)

[1, 2, 3, 5]
[1, 2, 3, 5]
[1, 2, 3, 5, 8]
[1, 2, 3, 5, 8]


#### Scenario 2

In [115]:
# What's happening here?
a = [1, 2, 3, 5] # Define a list container and point at it through pointer a
print(a)
b = a       # A new pointer b pointing to the same container as pointer a
print(b)    # Pointer b points to the same container as a
a.append(8) # Access container from a and append value '8' to the same container / in the same location
print(a)    # Pointer a points to the same modified container
print(b)    # Pointer b also points to the same modified container

[1, 2, 3, 5]
[1, 2, 3, 5]
[1, 2, 3, 5, 8]
[1, 2, 3, 5, 8]


*Note*: Applying list-specific methods on list objects (`append`, `pop`, `insert`...) does NOT create a new container in memory; the same old container is being modified.

#### Scenario 3

In [116]:
# What's happening here?
a = [1, 2, 3, 5] 
print(a)
b = a       
print(b)    
b[0] = 7        
print(a)    
print(b)

[1, 2, 3, 5]
[1, 2, 3, 5]
[7, 2, 3, 5]
[7, 2, 3, 5]


#### Scenario 3

In [117]:
# What's happening here?
a = [1, 2, 3, 5] # Define a list container and point at it through pointer a
print(a)
b = a     # A new pointer b pointing to the same container as pointer a
print(b)  # Pointer b points to the same container as a
b[0] = 7  # Modify first item in the container via pointer b
print(a)  # Pointer a points to the same modified container
print(b)  # Pointer b also points to the same modified container

[1, 2, 3, 5]
[1, 2, 3, 5]
[7, 2, 3, 5]
[7, 2, 3, 5]


*Note*: Accessing list items through `[ ]` operates directly on the same container; no copies created.

#### Scenario 4

In [118]:
# What's happening here?
a = [1, 2, 3, 5] 
print(a)
b = a[:]    
print(b)    
b[0] = 7        
print(a)    
print(b)

[1, 2, 3, 5]
[1, 2, 3, 5]
[1, 2, 3, 5]
[7, 2, 3, 5]


#### Scenario 4

In [119]:
# What's happening here?
a = [1, 2, 3, 5] # Define a list container and point at it through pointer a
print(a)
b = a[:]  # !!! Create a copy of the container, store somewhere else in memory and point at it via pointer b
print(b)  # Pointer b points to a DIFFERENT container that just has the same list values as a's container
b[0] = 7  # Modify first item in the SECOND container via pointer b
print(a)  # Pointer a still points to the first container 
print(b)  # Pointer b still points to the second container

[1, 2, 3, 5]
[1, 2, 3, 5]
[1, 2, 3, 5]
[7, 2, 3, 5]


*Note*: Blank slicing a list - `[:]` - creates a copy of that list.

Check out even more crazy stuff you can do in Python:

https://github.com/satwikkansal/wtfpython

## Tuples

- Similar to lists
- Can contain duplicates
- Immutable
- Defined by ``(1, 2, 3)`` or simply ``1, 2, 3`` 

In [120]:
t = (1, 2, 3)
t

(1, 2, 3)

In [121]:
t = 1, 2, 3
t

(1, 2, 3)

In [122]:
len(t)

3

### Elements cannot be changed

```python
t[0] = 5
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-86-6dd06f73cec4> in <module>()
----> 1 t[0] = 5

TypeError: 'tuple' object does not support item assignment
```

### Return types of functions are often tuples


In [123]:
x = 0.125
x.as_integer_ratio()

(1, 8)

In [124]:
numerator, denominator = x.as_integer_ratio()
numerator / denominator

0.125

## Sets
- Unordered collections of unique items
- Support set operations
- Defined by ``{1, 2, 3}`` 

In [125]:
primes = {2, 3, 5, 7}
odds = {1, 3, 5, 7, 9}

### Union
items appearing in either set

In [126]:
primes = {2, 3, 5, 7}
odds = {1, 3, 5, 7, 9}
primes | odds      # with an operator
primes.union(odds) # equivalently with a method

{1, 2, 3, 5, 7, 9}

### Intersection
items appearing in both sets

In [127]:
primes = {2, 3, 5, 7}
odds = {1, 3, 5, 7, 9}
primes & odds             # with an operator
primes.intersection(odds) # equivalently with a method

{3, 5, 7}

### Difference
items appearing in one but not other set

In [128]:
primes = {2, 3, 5, 7}
odds = {1, 3, 5, 7, 9}
primes - odds           # with an operator
primes.difference(odds) # equivalently with a method

{2}

### Symmetric difference
items appearing in only one set

In [129]:
primes = {2, 3, 5, 7}
odds = {1, 3, 5, 7, 9}
primes ^ odds                     # with an operator
primes.symmetric_difference(odds) # equivalently with a method

{1, 2, 9}

## Dictionaries
- Hash table
- Extremely flexible and versatile
- Fast access
- Unordered
- Defined by ``key:value`` pairs within curly braces: ``{'a':1, 'b':2, 'c':3}``

In [130]:
numbers = {'one':1, 'two':2, 'three':3}

In [131]:
# Access a value via the key
numbers['two']

2

In [132]:
# Set a new key:value pair
numbers['ninety'] = 90
numbers

{'one': 1, 'two': 2, 'three': 3, 'ninety': 90}

## Anaconda setup

### Change path to new conda env

- Click on ``Configure Conda``

<img src="figures/Anaconda_preferences1.png" width="600">

- Add or change the ``envs_dirs`` as needed

<img src="figures/Anaconda_conda_settings.png" width="600">

- Any new conda envs created in the future will be in this directory.

### Create new conda env with Python 3.9

- Go to ``Environments``
- Click on ``Create``

<img src="figures/Anaconda_new_env1.png" width="600">

- Select Python 3.9 and then ``Create``

<img src="figures/Anaconda_new_env2.png" width="600">

- If you get errors, don't panic. Try this command in the conda shell:
``conda clean --all``

- After moving to the new env with a different Python version, back in the Anaconda Navigator ``Home``, you may see ``Install`` instead of ``Launch`` for Jupyter Notebook, CMD.exe Prompt, etc. That is OK. Simply install again and you will be able to launch them.

### Optional but very useful: change base dir for Jupyter Notebook

- Generate the ``jupyter_notebook_config.py`` with this command in the shell:

``jupyter notebook --generate-config``

- Uncomment the setting ``c.ServerApp.root_dir`` and specify a folder you prefer
- Make sure any backslashes are escaped!